# app/sources.py
# page_type: fees | admissions | deadlines | programs | aid | about

SOURCES = [
    # HARVARD
    {"university": "Harvard", "page_type": "fees",
     "url": "https://college.harvard.edu/financial-aid/how-aid-works"},
    {"university": "Harvard", "page_type": "admissions",
     "url": "https://college.harvard.edu/resources/faq/are-there-secondary-school-course-requirements-admission"},
    {"university": "Harvard", "page_type": "programs",
     "url": "https://college.harvard.edu/academics/liberal-arts-sciences/concentrations"},
    {"university": "Harvard", "page_type": "deadlines",
     "url": "https://college.harvard.edu/admissions/apply/first-year-applicants"},
    {"university": "Harvard", "page_type": "aid",
     "url": "https://college.harvard.edu/financial-aid"},
    {"university": "Harvard", "page_type": "about",
     "url": "https://college.harvard.edu/"},

    # YALE
    {"university": "Yale", "page_type": "fees",
     "url": "https://student-accounts.yale.edu/tuition-and-fees"},
    {"university": "Yale", "page_type": "admissions",
     "url": "https://admissions.yale.edu/advice-selecting-high-school-courses"},
    {"university": "Yale", "page_type": "deadlines",
     "url": "https://admissions.yale.edu/application-deadlines"},
    {"university": "Yale", "page_type": "programs",
     "url": "https://catalog.yale.edu/ycps/majors-in-yale-college/"},
    {"university": "Yale", "page_type": "aid",
     "url": "https://finaid.yale.edu/"},
    {"university": "Yale", "page_type": "about",
     "url": "https://admissions.yale.edu/"},

    # PRINCETON
    {"university": "Princeton", "page_type": "fees",
     "url": "https://admission.princeton.edu/cost-aid/fees-payment-options"},
    {"university": "Princeton", "page_type": "admissions",
     "url": "https://admission.princeton.edu/apply/before-you-apply"},
    {"university": "Princeton", "page_type": "deadlines",
     "url": "https://admission.princeton.edu/apply/first-year-application-dates-deadlines"},
    {"university": "Princeton", "page_type": "programs",
     "url": "https://www.princeton.edu/academics/areas-of-study"},
    {"university": "Princeton", "page_type": "aid",
     "url": "https://admission.princeton.edu/cost-aid/financial-aid-basics"},
    {"university": "Princeton", "page_type": "about",
     "url": "https://www.princeton.edu/"},

    # BROWN
{"university": "Brown", "page_type": "fees",
 "url": "https://admission.brown.edu/tuition-aid/tuition-fees"},
{"university": "Brown", "page_type": "admissions",
 "url": "https://admission.brown.edu/first-year/application-checklist"},
{"university": "Brown", "page_type": "programs",
 "url": "https://bulletin.brown.edu/the-college/concentrations/"},
{"university": "Brown", "page_type": "aid",
 "url": "https://financialaid.brown.edu/"},
{"university": "Brown", "page_type": "about",
 "url": "https://www.brown.edu/"},

    # COLUMBIA
    {"university": "Columbia", "page_type": "fees",
     "url": "https://undergrad.admissions.columbia.edu/affordability/cost"},
    {"university": "Columbia", "page_type": "admissions",
     "url": "https://undergrad.admissions.columbia.edu/apply/firstyear"},
    {"university": "Columbia", "page_type": "deadlines",
     "url": "https://undergrad.admissions.columbia.edu/apply/firstyear"},
    {"university": "Columbia", "page_type": "programs",
     "url": "https://www.college.columbia.edu/academics/programs"},
    {"university": "Columbia", "page_type": "aid",
     "url": "https://undergrad.admissions.columbia.edu/affordability"},
    {"university": "Columbia", "page_type": "about",
     "url": "https://undergrad.admissions.columbia.edu/"},

    # CORNELL
    {"university": "Cornell", "page_type": "fees",
     "url": "https://finaid.cornell.edu/cost-to-attend"},
    {"university": "Cornell", "page_type": "admissions",
     "url": "https://admissions.cornell.edu/how-to-apply/first-year-applicants/college-and-school-admissions-requirements"},
    {"university": "Cornell", "page_type": "deadlines",
     "url": "https://admissions.cornell.edu/how-to-apply/first-year-applicants"},
    {"university": "Cornell", "page_type": "programs",
     "url": "https://admissions.cornell.edu/academics/majors"},
    {"university": "Cornell", "page_type": "aid",
     "url": "https://finaid.cornell.edu/"},
    {"university": "Cornell", "page_type": "about",
     "url": "https://admissions.cornell.edu/"},

    # DARTMOUTH
    {"university": "Dartmouth", "page_type": "fees",
     "url": "https://financialaid.dartmouth.edu/cost-attendance"},
    {"university": "Dartmouth", "page_type": "admissions",
     "url": "https://admissions.dartmouth.edu/apply-dartmouth"},
    {"university": "Dartmouth", "page_type": "deadlines",
     "url": "https://admissions.dartmouth.edu/glossary-term/application-deadline"},
    {"university": "Dartmouth", "page_type": "programs",
     "url": "https://home.dartmouth.edu/degrees"},
    {"university": "Dartmouth", "page_type": "aid",
     "url": "https://financialaid.dartmouth.edu/"},
    {"university": "Dartmouth", "page_type": "about",
     "url": "https://home.dartmouth.edu/dartmouth"},

    # UPENN
    {"university": "UPenn", "page_type": "fees",
     "url": "https://srfs.upenn.edu/costs-budgeting/undergraduate-tuition-and-fees"},
    {"university": "UPenn", "page_type": "admissions",
     "url": "https://admissions.upenn.edu/how-to-apply/first-year-applicants/application-requirements"},
    {"university": "UPenn", "page_type": "deadlines",
     "url": "https://admissions.upenn.edu/how-to-apply/first-year-applicants"},
    {"university": "UPenn", "page_type": "programs",
     "url": "https://admissions.upenn.edu/academics-programs"},
    {"university": "UPenn", "page_type": "aid",
     "url": "https://srfs.upenn.edu/financial-aid"},
    {"university": "UPenn", "page_type": "about",
     "url": "https://admissions.upenn.edu/"},
]